Standardise to use natural log
nfidd/nfidd pull request #226
Opened 2024-06-22 21:23 UTC by seabbs

We have a single (?) instance of plotting with log10 and otherwise use the natural log. I think the natural log makes more sense given that is the scale we are modelling on (and teaching epi processes on) but happy with either as long as we stick to one.

2024-06-22 21:55 UTC, sbfnk requested changes

2024-06-22 21:55 UTC, sbfnk commented on sessions/forecasting-concepts.qmd
> +  scale_y_continuous(trans = "log") +
```suggestion
  scale_y_log() +
```
otherwise the y axis will look rubbish

2024-06-22 22:18 UTC, sbfnk approved these changes

2024-06-22 22:36 UTC, sbfnk commented
Turns out `scale_y_log()` doesn't exist - thinking about this though we're only talking about axis labels, right? I think having 10, 100, 1000 etc. works better than what looks like random numbers.

2024-06-23 08:48 UTC, seabbs commented
Then we need to make them all the same and explain why the lines aren't linear on the log10 scale?

2024-06-23 09:17 UTC, sbfnk commented
why wouldn't they be, given that changing the base only amounts to a constant scaling on the log scale

2024-06-23 09:41 UTC, seabbs commented
> why wouldn't they be, given that changing the base only amounts to a constant scaling on the log scale

Yes your right/

2024-06-23 10:08 UTC, sbfnk commented
So can we close this? (and I'd argue do the reverse, i.e. change the plot in forecasting-conectps to log10)

2024-06-23 10:39 UTC, closed without merging